-- RT PGY Feedback Platform v7.1
-- Supabase PostgreSQL schema + Row Level Security
-- Run this once in Supabase Dashboard > SQL Editor.

create table if not exists public.feedback_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  client_id text not null,
  record_created_at timestamptz not null default now(),
  assessment_date date not null,
  learner_code text not null check (char_length(learner_code) between 1 and 24),
  care_population text not null check (care_population in ('adult','pediatric')),
  assessment_tool text not null check (assessment_tool in ('epa','mini','dops','cbd')),
  assessment_item text not null,
  assessment_rating text,
  observed_behavior text not null,
  selected_components jsonb not null default '[]'::jsonb,
  feedback text not null,
  take_home_message text,
  schema_version text not null default '7.1',
  updated_at timestamptz not null default now(),
  constraint feedback_records_user_client_unique unique (user_id, client_id)
);

create index if not exists feedback_records_user_date_idx
  on public.feedback_records (user_id, assessment_date desc);

create index if not exists feedback_records_user_tool_idx
  on public.feedback_records (user_id, assessment_tool);

create or replace function public.set_feedback_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_feedback_updated_at on public.feedback_records;
create trigger trg_feedback_updated_at
before update on public.feedback_records
for each row execute function public.set_feedback_updated_at();

alter table public.feedback_records enable row level security;

revoke all on public.feedback_records from anon;
grant select, insert, update, delete on public.feedback_records to authenticated;

drop policy if exists "feedback_select_own" on public.feedback_records;
create policy "feedback_select_own"
on public.feedback_records
for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "feedback_insert_own" on public.feedback_records;
create policy "feedback_insert_own"
on public.feedback_records
for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "feedback_update_own" on public.feedback_records;
create policy "feedback_update_own"
on public.feedback_records
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "feedback_delete_own" on public.feedback_records;
create policy "feedback_delete_own"
on public.feedback_records
for delete
to authenticated
using ((select auth.uid()) = user_id);
